#!/bin/bash
echo "-----------------------------------------------------------------------"
echo "Delete sym links"
rm -f  usr/bin/pycpulimit
echo "Symbolic links deleted."
echo "-----------------------------------------------------------------------"
exit 0
